spring.application.name=testcontainers-mariadb-postgresql
testcontainers.reuse.enable=true

# Create the tables if they don't yet exist
spring.sql.init.mode=always

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

logging.level.org.springframework.web=DEBUG
